# Hugo variables
#
baseurl = "https://bursakerja.vercel.app/"
languageCode = "id-id"
title = "Bursa Kerja 2021"
theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 10
# number of words to use for summary on home/category/tag pages (Default: 70)
summaryLength = 50
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Download Lagu Dangdut"
  url = "https://trianglefromthefire.com"

[[menu.sidebar]]
  name = "Sewa Baliho Jogja"
  url = "https://www.kilasjogja.com/sewa-baliho-di-jogja-dengan-harga-murah/"

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"


# Theme variables
#
[params]
  # Site author
  author = "Bang Jago"

  # Description/subtitle for homepage (can be Markdown)
  description = "Bursa kerja dengan penawaran gaji terbaik hanya di bursa.vercel.app tunggu apa lagi?"

  # Show header (default: true)
  #header_visible = true

  # Format dates with Go's time formatting
  #date_format = "12.02.2021"

  # verification string for Google Webmaster Tools
  google_verify_meta = "VXvqQtz10qhzv0fT5I1f4yiKXRA-jFnCY9Dx51rAQuw"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Kami adalah perusahaan penyedia jasa pencarian lowongan kerja di indonesia lebih dari 2000 pekerjaan baru setiap harinya yang kami informasikan di website ini, jika ada pertanyaan silahkan hubungi email ini joblokerid[at]gmail.com"

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
  # Bulgarian date format is dd.mm.yyyy
  #date_format = "02.01.2006"

# vim: ts=2 sw=2 et
